### ISSUE TITLE
Can't build the plugin with 4.13 ?

### ISSUE THREAD

**Issue by restani-mm** [OSVR/OSVR-Unreal#114]
Hi,

I'm having an issue when building the plugin for UE 4.13:

`osvr-unreal\osvrunreal\plugins\osvr\source\osvr\private\OSVRCustomPresentOpenGL.h(33): fatal error C1083: Cannot open include file: 'GL/glcorearb.h': No such file or directory`

The include directory seems to be missing. Where should GL/ be located ? I found it on the Engine's ThirdParty/OpenGL folder, but it doesn't seem to be picked up properly.

The plugin's source comes from today's master (commit 35b276d). Should I have pulled from another branch ?  

My goal is to have the plugin built from source on UE4.13 and run with the HDK2.0. The README.md states that building from source is the recommended method, is that still the case ?

Thanks for the insight.

**Comment by JeroMiya** [comment]
4.13 should have an updated plugin built in. The latest on master has some OpenGL code that should have been disabled by default but wasn't completely, leading to build errors. If you still want to use the latest on master, this PR should fix the build issues:
https://github.com/OSVR/OSVR-Unreal/pull/115

Otherwise, just remove your local project OSVR plugin and use the one that ships with 4.13.
