### ISSUE TITLE
Standard HMD functions are not implemented - GetDeviceName & GetTrackingSensorProperties

### ISSUE THREAD

**Issue by Jumbli** [OSVR/OSVR-Unreal#125]
GetDeviceName is in the UE4 OSVR plugin included in 4.13, but not in the github code version. This is handy when device specific code is needed.

GetTrackingSensorProperties is needed to draw camera bounds and tell the player when close to leaving the tracking area.

Are there any plans to include these in the near future? Thanks.

**Comment by JeroMiya** [comment]
At the moment, there isn't a way to get the tracking sensor properties from OSVR-Core (or indeed to query whether the tracking plugin even uses a single trackable sensor, or multiple trackable sensors, or inside out tracking with no trackable sensor, or wide area tracking, and so on), so that's probably not going to get an implementation in the near future.

As for GetDeviceName, I added this here:
https://github.com/OSVR/OSVR-Unreal/pull/144
