### ISSUE TITLE
ImportFromSDK.cmd doesn't work with spaces in the path

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/OSVR-Unreal#29]
The ImportFromSDK.cmd doesn't work when there are spaces in the source paths.

**Comment by rpavlik** [comment]
Presumably there are some places that need quotes added. Spaces in the path are always a pain. I usually try to be sure to quote everything but I didn't write the initial version of this batch file and I tried not to mess with it too much, since it seemed to actually work.

That batch file, ideally, should be replaced with something (powershell script and batch file?) that downloads the latest dlls and puts them in the right place automatically, but that would require some work on the access.osvr.com code to be able to provide an endpoint for the "most recent version", and/or making a nuget package with the client dlls, etc.

**Comment by OlafHaag** [comment]
The problem is, that the Unreal Engine 4 itself creates a folder for the UE4 Projects which name contains a space in User/Documents, titled "Unreal Projects", which is the default location for projects. That's why the ImportFromSDK.cmd doesn't work out-of-the-box and one has to look into the batch file, turn echo on and see what's going on to finally learn that the space is the problem.
